create table if not exists public.chat_messages (
    id bigint generated by default as identity primary key,
    session_id text not null,
    user_id text not null,
    role text not null,
    content text not null,
    created_at timestamptz not null default now(),
    constraint chat_messages_role_check check (role in ('user', 'assistant'))
);

create index if not exists chat_messages_session_created_at_idx
on public.chat_messages (session_id, created_at desc);

create index if not exists chat_messages_session_role_created_at_idx
on public.chat_messages (session_id, role, created_at desc);
